apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    #deployment own label name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      #match with pod template setting
  template:
    metadata:
      #label the pod
      #then you can match the lable from deployment specification setting
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 80
