apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-secret
spec:
  selector:
    matchLabels:
      app: test-secret-volume
  replicas: 1
  template:
    metadata:
      labels:
        app: test-secret-volume
    spec:
      containers:
      - name: test-secret-volume
        image: busybox
        args:
        - sleep
        - "86400"
        volumeMounts:
        - name: mysql-cred
          mountPath: "/projected-volume"
          readOnly: true
      volumes:
      - name: mysql-cred
        projected:
          sources:
          - secret:
              name: user
          - secret:
              name: pass
