apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
# default time is Opaque for arbitraty key-value pairs
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=
